### ISSUE TITLE
Support selector based policy templating

### ISSUE THREAD

**Issue by baluchicken** [cisco-open/camblet-driver#162]
## Problem Statement
Creating multiple policies becomes necessary when multiple users require identical access rights to a service. This process is not only error-prone but can also be tiresome

## Proposed Solution
Introduce templating functionality to streamline the creation of policies.

E.g.:
```
- selectors:
  - process:uid: [501, 1001]
    process:name: [curl, wrk]
    destination:port: [8000, 8080]
  certificate:
    workloadID: curl
  egress:
  - selectors:
    - app:label: traefik
    certificate:
      workloadID: specific-workload-id/[[process:uid]]/[[process:name]]
```
